---
- name: enable firewall ports for public
  shell: |
    firewall-cmd --permanent --zone=public --add-service=http
    firewall-cmd --permanent --zone=public --add-service=https
    firewall-cmd --permanent --zone=public --add-port=5601/tcp
    firewall-cmd --permanent --zone=public --add-port=5044/tcp
    firewall-cmd --reload
